-------------------------------------------------------------------------------
Test set: org.example.DoSomethingClassTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.056 s <<< FAILURE! - in org.example.DoSomethingClassTest
example3b2  Time elapsed: 0.007 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
expected: <The value of a was found in the int array.
The value of a was found in the int array.
> but was: <The value of a was found in the int array.
The value of b was found in the int array.
>
	at org.example.DoSomethingClassTest.example3b2(DoSomethingClassTest.java:111)

